insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Pepper - Cubanelle', 5, '$30.59', 5);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Pizza Pizza Dough', 7, '$72.27', 56);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Veal - Inside, Choice', 3, '$34.69', 27);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Vol Au Vents', 5, '$24.53', 90);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Apricots Fresh', 3, '$66.77', 4);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Chicken - Livers', 10, '$43.32', 2);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Sambuca - Opal Nera', 5, '$95.33', 55);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Cream - 10%', 8, '$78.55', 49);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Yogurt - Assorted Pack', 9, '$0.13', 58);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Pie Shells 10', 8, '$19.38', 42);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Chicken - Breast, 5 - 7 Oz', 2, '$92.85', 14);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Chocolate - Semi Sweet, Calets', 1, '$46.66', 7);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Cheese - Brie, Cups 125g', 3, '$59.25', 25);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Pie Shell - 9', 4, '$86.99', 35);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Bandage - Flexible Neon', 4, '$56.41', 34);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Carrots - Purple, Organic', 6, '$98.50', 95);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Potatoes - Fingerling 4 Oz', 4, '$85.40', 59);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Cake Sheet Combo Party Pack', 9, '$15.58', 54);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Wine - Peller Estates Late', 2, '$65.96', 64);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Tomatoes - Diced, Canned', 8, '$45.15', 1);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Waffle Stix', 2, '$13.81', 24);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Nori Sea Weed - Gold Label', 1, '$58.79', 46);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Trueblue - Blueberry', 2, '$19.27', 81);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Spring Roll Wrappers', 4, '$21.94', 11);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Squash - Sunburst', 9, '$68.23', 90);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Crab - Back Fin Meat, Canned', 2, '$28.53', 37);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Sobe - Cranberry Grapefruit', 3, '$44.82', 41);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Juice - Apple, 500 Ml', 5, '$46.72', 54);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Leeks - Baby, White', 4, '$0.32', 12);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Crab - Dungeness, Whole, live', 7, '$35.38', 85);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Club Soda - Schweppes, 355 Ml', 3, '$6.69', 12);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Tomatoes - Grape', 4, '$8.42', 7);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Rum - Cream, Amarula', 10, '$30.78', 95);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Wine - Domaine Boyar Royal', 6, '$62.27', 22);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Clam Nectar', 5, '$57.92', 96);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Squash - Sunburst', 2, '$69.83', 50);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Yogurt - Raspberry, 175 Gr', 4, '$49.73', 93);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Bread - Hot Dog Buns', 5, '$95.57', 19);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Compound - Rum', 10, '$64.14', 61);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Hummus - Spread', 8, '$19.51', 66);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Wanton Wrap', 6, '$8.97', 1);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Hummus - Spread', 4, '$52.65', 57);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Mix - Cappucino Cocktail', 3, '$17.69', 91);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Glove - Cutting', 9, '$35.72', 13);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Spice - Pepper Portions', 1, '$74.14', 100);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Muffin Batt - Choc Chk', 10, '$67.85', 45);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Tuna - Yellowfin', 4, '$12.88', 82);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Appetizer - Tarragon Chicken', 2, '$42.05', 78);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('V8 - Tropical Blend', 1, '$42.64', 41);
insert into Products (ProductName, CategoryID, UnitPrice, UnitsInStock) values ('Beef - Tenderlion, Center Cut', 6, '$14.59', 78);
